In [ ]:
import pandas as pd

In [ ]:

# with open("scraped_data/dataset1", "w", encoding="utf-8") as f:
#     f.write(res.text)

df = pd.read_csv("csv/IRIS.csv")
print(df, type(df))

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns] <class 'pandas.DataFrame'>

In [ ]:
df.head(10)
df.tail(10)
df.sample(5)

print(df.info())
print(df.describe())
print(df.nunique())

df.shape   #datatype

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    str
dtypes: float64(4), str(1)
memory usage: 6.0 KB
None
       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000
sepal_length    35
sepal_width     23
petal_length    43
petal_width     22
species          3
dtype: int64

(150, 5)

In [ ]:
df[["petal_width", "species"]]

     petal_width         species
0            0.2     Iris-setosa
1            0.2     Iris-setosa
2            0.2     Iris-setosa
3            0.2     Iris-setosa
4            0.2     Iris-setosa
..           ...             ...
145          2.3  Iris-virginica
146          1.9  Iris-virginica
147          2.0  Iris-virginica
148          2.3  Iris-virginica
149          1.8  Iris-virginica

[150 rows x 2 columns]

In [ ]:
print(df.loc[0:3])
print()
print(df.loc[0:3, ["sepal_length","sepal_width"]])
print()
print(df.iloc[1:4])
print()
print(df.iloc[2:5, 1:3])

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa

   sepal_length  sepal_width
0           5.1          3.5
1           4.9          3.0
2           4.7          3.2
3           4.6          3.1

   sepal_length  sepal_width  petal_length  petal_width      species
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa

   sepal_width  petal_length
2          3.2           1.3
3          3.1           1.5
4          3.6           1.4

In [ ]:

print(df.iloc[0:4, 2])
print()
print(df.loc[0:3, ["species"]])

print()
df.loc[2]
df.iloc[1]

0    1.4
1    1.4
2    1.3
3    1.5
Name: petal_length, dtype: float64

       species
0  Iris-setosa
1  Iris-setosa
2  Iris-setosa
3  Iris-setosa

sepal_length            4.9
sepal_width             3.0
petal_length            1.4
petal_width             0.2
species         Iris-setosa
Name: 1, dtype: object

In [ ]:
# filtering --

df[ (df["petal_length"] >= 3) & (df["petal_width"] <= 2) ]

df[ (df["petal_length"] >= 3) & (df["species"] == "Iris-virginica") ]

     sepal_length  sepal_width  petal_length  petal_width         species
100           6.3          3.3           6.0          2.5  Iris-virginica
101           5.8          2.7           5.1          1.9  Iris-virginica
102           7.1          3.0           5.9          2.1  Iris-virginica
103           6.3          2.9           5.6          1.8  Iris-virginica
104           6.5          3.0           5.8          2.2  Iris-virginica
105           7.6          3.0           6.6          2.1  Iris-virginica
106           4.9          2.5           4.5          1.7  Iris-virginica
107           7.3          2.9           6.3          1.8  Iris-virginica
108           6.7          2.5           5.8          1.8  Iris-virginica
109           7.2          3.6           6.1          2.5  Iris-virginica
110           6.5          3.2           5.1          2.0  Iris-virginica
111           6.4          2.7           5.3          1.9  Iris-virginica
112           6.8          3.0           5.5          2.1  Iris-virginica
113           5.7          2.5           5.0          2.0  Iris-virginica
114           5.8          2.8           5.1          2.4  Iris-virginica
115           6.4          3.2           5.3          2.3  Iris-virginica
116           6.5          3.0           5.5          1.8  Iris-virginica
117           7.7          3.8           6.7          2.2  Iris-virginica
118           7.7          2.6           6.9          2.3  Iris-virginica
119           6.0          2.2           5.0          1.5  Iris-virginica
120           6.9          3.2           5.7          2.3  Iris-virginica
121           5.6          2.8           4.9          2.0  Iris-virginica
122           7.7          2.8           6.7          2.0  Iris-virginica
123           6.3          2.7           4.9          1.8  Iris-virginica
124           6.7          3.3           5.7          2.1  Iris-virginica
125           7.2          3.2           6.0          1.8  Iris-virginica
126           6.2          2.8           4.8          1.8  Iris-virginica
127           6.1          3.0           4.9          1.8  Iris-virginica
128           6.4          2.8           5.6          2.1  Iris-virginica
129           7.2          3.0           5.8          1.6  Iris-virginica
130           7.4          2.8           6.1          1.9  Iris-virginica
131           7.9          3.8           6.4          2.0  Iris-virginica
132           6.4          2.8           5.6          2.2  Iris-virginica
133           6.3          2.8           5.1          1.5  Iris-virginica
134           6.1          2.6           5.6          1.4  Iris-virginica
135           7.7          3.0           6.1          2.3  Iris-virginica
136           6.3          3.4           5.6          2.4  Iris-virginica
137           6.4          3.1           5.5          1.8  Iris-virginica
138           6.0          3.0           4.8          1.8  Iris-virginica
139           6.9          3.1           5.4          2.1  Iris-virginica
140           6.7          3.1           5.6          2.4  Iris-virginica
141           6.9          3.1           5.1          2.3  Iris-virginica
142           5.8          2.7           5.1          1.9  Iris-virginica
143           6.8          3.2           5.9          2.3  Iris-virginica
144           6.7          3.3           5.7          2.5  Iris-virginica
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

In [ ]:
# cleaning -

df.isnull().sum()

df.isna().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [ ]:
# grouping-

df.groupby("species")["petal_length"].mean()
df.groupby("species")["petal_length"].min()
df.groupby("species")["petal_length"].max()

df[["petal_width", "species"]].min()
df[["petal_width", "species"]].max()

df["petal_length"].min()
df["petal_length"].max()
df["petal_length"].mean()

np.float64(3.758666666666666)

In [ ]:

# new col - 

# df2 = df.copy()
# df2.columns
# new_col = [col for col in df2.columns if col != "id"] + ["id"]
# print(new_col)


# df3 = df.copy()
# df3.columns
# col2 = [col for col in df3.columns if col != "petal_ratio"] + ["petal_ratio"]
# print(col2)


df["petal_ratio"] = df["petal_length"] / df["petal_width"]
print(df["petal_ratio"])

result = df.groupby("species")["petal_ratio"].mean()
print(result)

0      7.000000
1      7.000000
2      6.500000
3      7.500000
4      7.000000
         ...
145    2.260870
146    2.631579
147    2.600000
148    2.347826
149    2.833333
Name: petal_ratio, Length: 150, dtype: float64

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    str
 5   petal_ratio   150 non-null    float64
dtypes: float64(5), str(1)
memory usage: 7.2 KB